config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root to: "places#index"

  resources :places do
    get '/places/:id', to: 'places#fight', as: 'fight'
  end

  resources :users
  #   resources :places
  #   get "fight", to: 'users#'
  # end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  has_many :items

  validates :user_id, :presence => true
  validates :amount, :presence => true

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory

  validates :name, :presence => true
  validates :value, :presence => true
  validates :inventory_id, :presence => true

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  belongs_to :place

  validates :name, :presence => true
  validates :place_id, :presence => true
  validates :attack, :presence => true
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :monsters

  validates :name, :presence => true

  def self.scout(place)
      place1 = Place.all.where(xcoord: place.xcoord).where(ycoord: (place.ycoord + 1)).first
      place1.update_attributes(:accessible? => true) if place1

      place2 = Place.all.where(xcoord: place.xcoord).where(ycoord: (place.ycoord - 1)).first
      place2.update_attributes(:accessible? => true) if place2

      place3 = Place.all.where(ycoord: place.ycoord).where(xcoord: (place.xcoord + 1)).first
      place3.update_attributes(:accessible? => true) if place3

      place4 = Place.all.where(ycoord: place.ycoord).where(xcoord: (place.xcoord - 1)).first
      place4.update_attributes(:accessible? => true) if place4
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :inventory

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :avatar) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :avatar) }
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @user = current_user
    @monster = @place.monsters.first
    if @place.accessible? == false
      flash[:alert] = "you shall not pass (yet) !"
      redirect_to places_path()
    end
  end

  def create
  end

  def fight
    @user = User.find(params[:id])
    @place = Place.find(params[:place_id])
    @monster = @place.monsters.first
    userdmg = rand(0..@user.attack)
    monsterdmg = rand(0..@monster.attack)

    if userdmg >= monsterdmg && @place.accessible?
      @monster.update_attributes(:alive? => false)
      @monster.update_attributes(:token => "images/thumb/gravestone.png")
      @place.update_attributes(:accessible? => true)
      flash[:alert] = "you won"
      Place.scout(@place)
      redirect_to places_path()

    else
      flash[:alert] = "the monster takes your cookies, you cry"
      redirect_to places_path()
    end
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :new, :create]
  def index
  end

  def new

  end

  def create
  end


end

# Remember:
# http://stackoverflow.com/questions/11678508/email-cant-be-blank-devise-using-username-or-email
# https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Literals
# update_attributes(:updated_at => 100.years.ago)

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RpgRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= link_to "HOME", places_path %>
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= image_tag(current_user.avatar.url(:thumb)) %>
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/places/index.html.erb
<div id="gameBoard" class = "fog_of_war">
  <div class="row" id="row-0">
    <%= link_to place_path(@places.where(id: 1).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 1).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 1).first.accessible? == true %>" id="1"></div> <% end %>
    <%= link_to place_path(@places.where(id: 2).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 2).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 2).first.accessible? == true %>" id="2"></div> <% end %>
    <%= link_to place_path(@places.where(id: 3).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 3).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 3).first.accessible? == true %>" id="3"></div> <% end %>
    <%= link_to place_path(@places.where(id: 4).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 4).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 4).first.accessible? == true %>" id="4"></div> <% end %>
    <%= link_to place_path(@places.where(id: 5).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 5).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 5).first.accessible? == true %>" id="5"></div> <% end %>
  </div>
  <div class="row" id="row-1">
    <%= link_to place_path(@places.where(id: 6).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 6).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 6).first.accessible? == true %>" id="6"></div> <% end %>
    <%= link_to place_path(@places.where(id: 7).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 7).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 7).first.accessible? == true %>" id="7"></div> <% end %>
    <%= link_to place_path(@places.where(id: 8).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 8).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 8).first.accessible? == true %>" id="8"></div> <% end %>
    <%= link_to place_path(@places.where(id: 9).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 9).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 9).first.accessible? == true %>" id="9"></div> <% end %>
    <%= link_to place_path(@places.where(id: 10).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 10).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 10).first.accessible? == true %>" id="10"></div> <% end %>

  </div>
  <div class="row" id="row-2">
    <%= link_to place_path(@places.where(id: 11).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 11).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 11).first.accessible? == true %>" id="11"></div> <% end %>
    <%= link_to place_path(@places.where(id: 12).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 12).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 12).first.accessible? == true %>" id="12"></div> <% end %>
    <%= link_to place_path(@places.where(id: 13).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 13).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 13).first.accessible? == true %>" id="13"></div> <% end %>
    <%= link_to place_path(@places.where(id: 14).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 14).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 14).first.accessible? == true %>" id="14"></div> <% end %>
    <%= link_to place_path(@places.where(id: 15).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 15).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 15).first.accessible? == true %>" id="15"></div> <% end %>

  </div>
  <div class="row" id="row-3">
    <%= link_to place_path(@places.where(id: 16).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 16).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 16).first.accessible? == true %>" id="16"></div> <% end %>
    <%= link_to place_path(@places.where(id: 17).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 17).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 17).first.accessible? == true %>" id="17"></div> <% end %>
    <%= link_to place_path(@places.where(id: 18).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 18).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 18).first.accessible? == true %>" id="18"></div> <% end %>
    <%= link_to place_path(@places.where(id: 19).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 19).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 19).first.accessible? == true %>" id="19"></div> <% end %>
    <%= link_to place_path(@places.where(id: 20).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 20).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 20).first.accessible? == true %>" id="20"></div> <% end %>

  </div>
  <div class="row" id="row-4">
    <%= link_to place_path(@places.where(id: 21).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 21).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 21).first.accessible? == true %>" id="21"></div> <% end %>
    <%= link_to place_path(@places.where(id: 22).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 22).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 22).first.accessible? == true %>" id="22"></div> <% end %>
    <%= link_to place_path(@places.where(id: 23).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 23).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 23).first.accessible? == true %>" id="23"></div> <% end %>
    <%= link_to place_path(@places.where(id: 24).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 24).first.monsters.first.token  %>') center center no-repeat" class="place<%= ' scouted' if Place.all.where(id: 24).first.accessible? == true %>" id="24"></div> <% end %>
    <%= link_to place_path(@places.where(id: 25).pluck(:id)[0]) do %><div style="background: url('<%= Place.all.where(id: 25).first.monsters.first.token  %>') center center no-repeat" class="place scouted" id="25"></div> <% end %>
  </div>
</div>

app/views/places/show.html.erb
<div class = "battle_block">
  <div class = "space_block">
    <p>You are now in <%= @place.name %>.</p>

    <% if @place.monsters.first.alive? %>
      <%= @place.monsters.first.name %> has appeared!
      <p>he has <%= @place.monsters.first.attack %> attack damage!</p>
    <% else %>
      <p>Here lies the grave of <%= @place.monsters.first.name %></p>
      <p>Ruthlessly slaughtered by <%= @user.username %></p>
    <%end %>
  </div>
  <div class="user_block stat_block">
    Character-Name: <%= @user.username %><br>
    Attack-Range: 0 - <%= @user.attack %><br>
    <%= image_tag(current_user.avatar.url(:thumb)) %>
  </div>
  <div class="stat_block">
    <% if @place.monsters.first.alive? %>
      <%= link_to 'fight', place_fight_path(@monster, @user), {controller: "places", action: "fight", :place => @place, :monster => @monster} %>
    <% else %>
      <%= link_to "Home", places_path %>
    <%end %>
  </div>

  <% if @place.monsters.first.alive? %>
    <div class="monster_block stat_block">
      Monster-Name: <%= @monster.name %><br>
      Attack-Range: 0 - <%= @monster.attack %><br>
      <img src="/images/thumb/monster.png" alt="Monster Avatar" />
    </div>
  <% else %>
    <div class="monster_block stat_block">
      <p>
        Corpses litter your path
      </p>
      <img src="/images/thumb/gravestone.png" alt="Monster Dead" />
    </div>
  <%end %>
</div>